spring:
  application:
    name: callme
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/c9realm/protocol/openid-connect/certs
#          issuer-uri: http://localhost:8080/realms/c9realm

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE

server.port: 8040