spring:
  application:
    name: gateway


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/c9realm/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/c9realm
        registration:
          c9-client:
            provider: keycloak
            client-id: c9-client
            scope: openid
            #client-secret: rEAjbk8keRpI5l6l1fRGX9ANGWJ0klMQ
            #authorization-grant-type: authorization_code
#          keycloak-without-test-scope:
#            provider: keycloak
#            client-id: spring-without-test-scope
#            client-secret: f6fc369d-49ce-4132-8282-5b5d413eba23
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/spring-without-test-scope"

server.port: 8060

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE